const styles = {
  container: {
    padding: 20,
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    maxWidth: "100vw",
    height: "100vh",
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    backgroundColor: "#111",
    color: "#fff",
  },
  title: {
    textAlign: "center",
    marginBottom: 20,
    color: "#ff6600",
    fontSize: "2rem",
    fontWeight: "bold",
  },
  chatBox: {
    flex: 1,
    border: "1px solid #444",
    overflowY: "auto",
    padding: 10,
    marginBottom: 10,
    background: "#1f1f1f",
    borderRadius: 12,
    display: "flex",
    flexDirection: "column",
    gap: 8,
    boxShadow: "0 4px 8px rgba(0, 0, 0, 0.2)",
  },
  userMsg: {
    alignSelf: "flex-end",
    backgroundColor: "#ff6600",
    color: "#fff",
    padding: "10px 15px",
    borderRadius: 16,
    margin: "5px 0",
    maxWidth: "75%",
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.2)",
  },
  botMsg: {
    alignSelf: "flex-start",
    backgroundColor: "#333",
    color: "#fff",
    padding: "10px 15px",
    borderRadius: 16,
    margin: "5px 0",
    maxWidth: "75%",
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.2)",
  },
  inputArea: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    padding: "10px 0",
    borderTop: "1px solid #444",
  },
  input: {
    flex: 1,
    padding: "12px",
    fontSize: 16,
    border: "1px solid #444",
    borderRadius: 12,
    backgroundColor: "#2a2a2a",
    color: "#fff",
    outline: "none",
    transition: "all 0.3s ease",
  },
  inputFocused: {
    borderColor: "#ff6600",
    boxShadow: "0 0 5px rgba(255, 102, 0, 0.5)",
  },
  button: {
    padding: "12px 20px",
    background: "#ff6600",
    color: "#fff",
    border: "none",
    borderRadius: 12,
    cursor: "pointer",
    fontSize: "16px",
    transition: "background 0.3s ease",
  },
  buttonHover: {
    background: "#e55a00",
  },
  footer: {
    display: "flex",
    justifyContent: "center",
    gap: "20px",
    padding: "15px 0",
    borderTop: "1px solid #444",
    marginTop: "10px",
  },
  link: {
    color: "#ff6600",
    textDecoration: "none",
    fontWeight: "bold",
    transition: "color 0.3s",
  },
};

export default styles;
